---

- hosts: localhost

  tasks:
    - name: 1. Check variables passed from AAP
      debug:
        msg:
          vm_name: "{{ vm_name | default('❌ undefined') }}"
          image_id: "{{ image_id | default('❌ undefined') }}"
          instance_type: "{{ instance_type | default('❌ undefined') }}"
          key_name: "{{ key_name | default('❌ undefined') }}"
          security_group: "{{ security_group | default('❌ undefined') }}"
          region_name: "{{ region_name | default('❌ undefined') }}"
    
    - name: 2. Verify AWS credentials by calling STS GetCallerIdentity
      amazon.aws.aws_caller_info:
      register: aws_caller

    - name: 3. Show AWS credential test result
      debug:
        msg:
          - "✅ AWS Credential authentication succeeded"
          - "Account ID: {{ aws_caller.account }}"
          - "User ARN: {{ aws_caller.arn }}

    - name: Create ec2 vm
      amazon.aws.ec2_instance:
        name: "{{ vm_name }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
        region: "{{ region_name }}"
      register: vm_info

    - name: Print vm information
      ansible.builtin.debug:
        var: vm_info
