---

- hosts: localhost

  tasks:
    - name: Verify AWS credentials by calling STS GetCallerIdentity
      amazon.aws.aws_caller_info:
      register: aws_caller
      ignore_errors: true

    - name: Show AWS credential test result
      debug:
        msg:
          - "✅ AWS Credential authentication succeeded"
          - "Account ID: {{ aws_caller.account | default('❌ Unknown (No account returned)') }}"
          - "User ARN: {{ aws_caller.arn | default('❌ Unknown (No ARN returned)') }}"
      when: aws_caller is defined and aws_caller.failed is not defined

    - name: Handle failed AWS credential check
      debug:
        msg:
          - "❌ AWS credential authentication failed!"
          - "Check if your AWS Access Key / Secret Key are correctly set in AAP Credentials."
      when: aws_caller is failed or (aws_caller.account is not defined)

    - name: Create ec2 vm
      amazon.aws.ec2_instance:
        name: "{{ vm_name }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
        region: "{{ region_name }}"
      register: vm_info

    - name: Print vm information
      ansible.builtin.debug:
        var: vm_info
