---

- hosts: db
  vars_files:
    - mysecret.yml

  tasks:
  - name: Create User {{ user }}
    ansible.builtin.user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
      state: present
